### ISSUE TITLE
TypeError when trying to redact a circlular object

### ISSUE THREAD

**Issue by MatthewClair** [rcjpisani/redactyl.js#12]
Attempting to redact an object with a circular reference causes an error.

Test file:
```javascript
const Redactyl = require('redactyl.js')
const data = {}
data.data = data
const redactyl = new Redactyl()
redactyl.redact(data)
```

Output: 
```/home/matt/tmp/node_modules/redactyl.js/src/index.js:45
    let redacted = JSON.parse(JSON.stringify(json));
                                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'data' closes the circle
    at JSON.stringify (<anonymous>)
    at Redactyl.redact (/home/matt/tmp/node_modules/redactyl.js/src/index.js:45:36)
    at Object.<anonymous> (/home/matt/tmp/test.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47```

**Comment by rcjpisani** [comment]
Resolved in https://github.com/rcjpisani/redactyl.js/pull/15
